/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.EUsuarios;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import AccesoDatos.Hash;
import Modelos.Usuarios;


public class FrmEnviarCorreo extends javax.swing.JFrame {
    
    Usuarios clsUsuario = new Usuarios();
    
    private final Properties properties = new Properties();
    
    /**
     * Creates new form FrmEnviarCorreo
     */
    public FrmEnviarCorreo() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnEnviarCorreo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recuperación de Contraseñas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("CORREO");

        btnEnviarCorreo.setBackground(new java.awt.Color(70, 70, 255));
        btnEnviarCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnviarCorreo.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarCorreo.setText("RECUPERAR CONTRASEÑA");
        btnEnviarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnEnviarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCorreoActionPerformed
        // TODO add your handling code here:
        
        try{
            
            String messageOut;
            String username = Module.userNameMail;
            String password = Module.passwordMail;
            String email = this.txtCorreo.getText().trim();
            String token = Hash.getRandomString(6);
            Session session;
            
            if (email.equals("")) {
                this.txtCorreo.requestFocus();
                JOptionPane.showMessageDialog(null, "Ingrese un correo electrónico", Module.titleMessage, JOptionPane.CANCEL_OPTION);
                return;
            }
            if (!validarEmail(email)) {
                JOptionPane.showMessageDialog(null, "El correo electrónico no es válido", Module.titleMessage, JOptionPane.CANCEL_OPTION);
                return;
            }
            
            ArrayList arrayList = clsUsuario.searchByEmail(email);
            if(arrayList.isEmpty()){
                JOptionPane.showMessageDialog(null, "No existe el correo en el sistema", Module.titleMessage, JOptionPane.CANCEL_OPTION);
                return;
            }
            
            EUsuarios usuario = (EUsuarios)arrayList.get(0);
            String nombreUsuario = usuario.getNombres();
            String clave = Hash.decrypt(usuario.getClave());
            
            EUsuarios objUsu = new EUsuarios();
            objUsu.setId(usuario.getId());
            objUsu.setToken(token);
            messageOut = clsUsuario.updateToken(objUsu);
            if(!messageOut.equals("Actualizado correctamente")){
                JOptionPane.showMessageDialog(null, messageOut, Module.titleMessage, JOptionPane.CANCEL_OPTION);
                return;
            }
            
            String subject = "Recuperación de contraseña";
            String body = "<p>Buenos días "+nombreUsuario+" </p> </br>" +
                "<p> Usted ha solicitado recuperar su conntraseña. Le informamos que su contraseña es la siguiente: <b>"+clave+"</b>"+
                "Si desea cambiar su contraseña, debe ingresar el siguiente código <b>"+token+"</b> . <br>"+
                "en el formulario para validar que es usted el que ha realizado esta solicitud.</p>" +
                "<p>Si usted no ha realizado esta solicitud, le invitamos a omitir el correo electrónico </p>"+
                "<p></p><p>Gracias...</p>"+
                "<p><b>El equipo de "+Module.titleMessage+"</b></p>";
            
           /* properties.put("mail.smtp.host", Module.serverHost);
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.port", Module.serverPort);
            properties.put("mail.smtp.mail.sender", username);
            properties.put("mail.smtp.user", username);
            properties.put("mail.smtp.auth", "true");
*/
            properties.put("mail.smtp.host", Module.serverHost);
            properties.put("mail.smtp.ssl.trust", Module.serverHost);
            properties.setProperty("mail.smtp.starttls.enable", "true");
            properties.setProperty("mail.smtp.port", Module.serverPort);
            //properties.put("mail.smtp.mail.sender", username);
            properties.setProperty("mail.smtp.user", username);
            properties.setProperty("mail.smtp.ssl.protocols", "TLSv1.2");
            properties.setProperty("mail.smtp.auth", "true");
            
            session = Session.getDefaultInstance(properties);
            
            MimeMessage message = new MimeMessage(session);
            //message.setFrom(new InternetAddress((String)properties.get("mail.smtp.mail.sender")));
             message.setFrom(new InternetAddress(username));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(email));
            message.setSubject(subject);
            message.setContent(body, "text/html");
            Transport t = session.getTransport("smtp");
            t.connect((String)properties.get("mail.smtp.user"), password);
            t.sendMessage(message, message.getAllRecipients());
            t.close();
            JOptionPane.showMessageDialog(null, "Mensaje enviado con éxito. \n Revise su correo por favor");
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString(), Module.titleMessage, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarCorreoActionPerformed
    
    private static boolean validarEmail(String email) {
        // Patron para validar el email
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(email);
        return mather.find();
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEnviarCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEnviarCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEnviarCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEnviarCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEnviarCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
