/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

//import com.sun.glass.events.KeyEvent;
import java.awt.event.KeyEvent;
import Negocio.ECategorias;
import Negocio.EComboBox;
import Negocio.ELaboratorios;
import Negocio.EMarcas;
import Negocio.EProductos;
import Negocio.EUnidadesMedida;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import Modelos.Laboratorios;
import Modelos.Categorias;
import Modelos.Marcas;
import Modelos.Productos;
import Modelos.UnidadesMedida;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;


public class FrmProductos extends javax.swing.JFrame {
    
    Productos clsProductos = new Productos();
    EForm formActive;
    private final int id;
    /**
     * Creates new form FrmProductos
     */
    public FrmProductos() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        
        llenarComboLaboratorio();
        llenarComboCategorias();
        llenarComboMarcas();
        llenarComboUndMedida();
        
        Border line = BorderFactory.createLineBorder(Color.DARK_GRAY);
        Border empty = new EmptyBorder(0, 10, 0, 0);
        CompoundBorder border = new CompoundBorder(line, empty);
        txtPrecioCompra.setBorder(border);
        txtPrecioVta.setBorder(border);
        txtProducto.setBorder(border);
        txtStockActual.setBorder(border);
        txtStockMaximo.setBorder(border);
        txtStockMinimo.setBorder(border);
        txtUtilidad.setBorder(border);
        
        formActive = Module.formActive;
        id = Module.id;
        
        if(id == 0){
            this.setTitle("Nuevo Producto");
        }else{
            this.setTitle("Editar Producto");
            
            ArrayList arrayList = clsProductos.searchById(id);
            EProductos producto = (EProductos)arrayList.get(0);
            
            try{
                
                this.setSelectedValue(cbxLaboratorio, producto.getLaboratorio().getId());
                this.setSelectedValue(cbxCategoria, producto.getCategoria().getId());
                this.setSelectedValue(cbxMarca, producto.getMarca().getId());
                this.setSelectedValue(cbxUndMedida, producto.getUndMedida().getId());
                this.txtProducto.setText(producto.getDescripcion());
                SimpleDateFormat fomatter=new SimpleDateFormat("yyyy-MM-dd");
                Date fechaVto = fomatter.parse(producto.getFechaVto());
                this.dtpFechaVto.setDate(fechaVto);
                this.txtStockMinimo.setText(producto.getStockMinimo()+"");
                this.txtStockMaximo.setText(producto.getStockMaximo()+"");
                this.txtStockActual.setText(producto.getStock()+"");
                this.txtPrecioCompra.setText(producto.getPrecioCompra()+"");
                this.txtUtilidad.setText(producto.getUtilidad()+"");
                this.txtPrecioVta.setText(producto.getPrecioVenta()+"");
                this.cbxEstado.setSelectedItem(producto.getEstado());

            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.toString(), Module.titleMessage, JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }
    
    private void llenarComboLaboratorio(){
        Laboratorios clsLaboratorios = new Laboratorios();
        cbxLaboratorio.setModel(clsLaboratorios.fillCombobox());
    }
    
    private void llenarComboCategorias(){
        Categorias clsCategoria = new Categorias();
        cbxCategoria.setModel(clsCategoria.fillCombobox());
    }
    
    private void llenarComboMarcas(){
        Marcas clsMarca = new Marcas();
        cbxMarca.setModel(clsMarca.fillCombobox());
    }
    
    private void llenarComboUndMedida(){
        UnidadesMedida clsUndMedida = new UnidadesMedida();
        cbxUndMedida.setModel(clsUndMedida.fillCombobox());
    }
    
    public void setSelectedValue(JComboBox comboBox, int value){
        EComboBox item;
        for (int i = 0; i < comboBox.getItemCount(); i++){
            item = (EComboBox)comboBox.getItemAt(i);
            if (item.getId() == value){
                comboBox.setSelectedIndex(i);
                break;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxCategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        dtpFechaVto = new com.toedter.calendar.JDateChooser();
        txtProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxMarca = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbxUndMedida = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtStockMinimo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStockMaximo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStockActual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtUtilidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPrecioVta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbxLaboratorio = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Producto");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cbxCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("PRODUCTO");

        btnGuardar.setBackground(new java.awt.Color(70, 70, 255));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        dtpFechaVto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("MARCA");

        cbxMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("UNIDAD MEDIDA");

        cbxUndMedida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("STOCK MINIMO");

        txtStockMinimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStockMinimo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtStockMinimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockMinimoKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("STOCK MÁXIMO");

        txtStockMaximo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStockMaximo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtStockMaximo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockMaximoKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("STOCK ACTUAL");

        txtStockActual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStockActual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtStockActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockActualKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("FECHA VTO");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("PRECIO COMPRA");

        txtPrecioCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrecioCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioCompraKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("UTILIDAD %");

        txtUtilidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUtilidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUtilidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUtilidadKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("PRECIO VENTA");

        txtPrecioVta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrecioVta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPrecioVta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioVtaKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("ESTADO");

        cbxEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("LABORATORIO");

        cbxLaboratorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("CATEGORIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxLaboratorio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProducto)
                            .addComponent(cbxMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxUndMedida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtStockMinimo)
                                    .addComponent(txtStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtStockMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dtpFechaVto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPrecioVta, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(cbxLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxUndMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtStockMinimo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtStockMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(dtpFechaVto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUtilidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPrecioVta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(28, 28, 28)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            
            EComboBox comboLab = (EComboBox) cbxLaboratorio.getSelectedItem();
            EComboBox comboCat = (EComboBox) cbxCategoria.getSelectedItem();
            EComboBox comboMar = (EComboBox) cbxMarca.getSelectedItem();
            EComboBox comboUnd = (EComboBox) cbxUndMedida.getSelectedItem();
            
            int laboratorioId = comboLab.getId();
            int categoriaId = comboCat.getId();
            int marcaId = comboMar.getId();
            int undMedidaId = comboUnd.getId();
            String nombre = this.txtProducto.getText().trim();
            int stockMinimo = Integer.parseInt(this.txtStockMinimo.getText().trim());
            int stockMaximo = Integer.parseInt(this.txtStockMaximo.getText().trim());
            int stockActual = Integer.parseInt(this.txtStockActual.getText().trim());
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String fechaVtoStr = formatter.format(dtpFechaVto.getDate());
            double precioCompra = Double.parseDouble(this.txtPrecioCompra.getText().trim());
            double utilidad = Double.parseDouble(this.txtUtilidad.getText().trim());
            double precioVta = Double.parseDouble(this.txtPrecioVta.getText().trim());
            String estado = this.cbxEstado.getSelectedItem().toString();
            
            if(nombre.equals("")){
                JOptionPane.showMessageDialog(null, "Ingrese el nombre del producto", Module.titleMessage, JOptionPane.CANCEL_OPTION);
            }else {
                String message;
                
                EProductos objProductos = new EProductos();
                
                ELaboratorios objLab = new ELaboratorios();
                ECategorias objCat = new ECategorias();
                EMarcas objMar = new EMarcas();
                EUnidadesMedida objUnd = new EUnidadesMedida();
                
                if(id != 0){
                    objProductos.setId(id);
                }
                objLab.setId(laboratorioId);
                objCat.setId(categoriaId);
                objMar.setId(marcaId);
                objUnd.setId(undMedidaId);
                
                objProductos.setLaboratorio(objLab);
                objProductos.setCategoria(objCat);
                objProductos.setMarca(objMar);
                objProductos.setUndMedida(objUnd);
                objProductos.setDescripcion(nombre);
                objProductos.setStockMinimo(stockMinimo);
                objProductos.setStockMaximo(stockMaximo);
                objProductos.setStock(stockActual);
                objProductos.setFechaVto(fechaVtoStr);
                objProductos.setPrecioCompra(precioCompra);
                objProductos.setUtilidad(utilidad);
                objProductos.setPrecioVenta(precioVta);
                objProductos.setEstado(estado);
                
                if(id == 0){
                    message = clsProductos.create(objProductos);
                    if(message.equals("Registrado correctamente")){
                        cleanForm();
                        JOptionPane.showMessageDialog(null, message, Module.titleMessage, JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(null, message, Module.titleMessage, JOptionPane.CANCEL_OPTION);
                    }
                }else{
                    message = clsProductos.update(objProductos);
                    if(message.equals("Actualizado correctamente")){
                        cleanForm();
                        this.dispose();
                        JOptionPane.showMessageDialog(null, message, Module.titleMessage, JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(null, message, Module.titleMessage, JOptionPane.CANCEL_OPTION);
                    }
                }
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString(), Module.titleMessage, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    private void cleanForm(){
        this.txtProducto.setText("");
        this.txtStockMinimo.setText("");
        this.txtStockMaximo.setText("");
        this.txtStockActual.setText("");
        this.txtPrecioCompra.setText("");
        this.txtUtilidad.setText("");
        this.txtPrecioVta.setText("");
        formActive.getCaller().loadTable();
        llenarComboLaboratorio();
        llenarComboCategorias();
        llenarComboMarcas();
        llenarComboUndMedida();
    }
    
    private void txtStockMinimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockMinimoKeyTyped
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();
        String codigo = txtStockMinimo.getText();
        int punto = codigo.indexOf(".")+1;
        
        if(punto == 0){
            if(!Character.isDigit(tecla) && tecla != java.awt.event.KeyEvent.VK_BACK_SPACE && tecla != KeyEvent.VK_PERIOD){
                evt.consume();
                getToolkit().beep();
            }
        }else{
            if(!Character.isDigit(tecla) && tecla != java.awt.event.KeyEvent.VK_BACK_SPACE){
                evt.consume();
                getToolkit().beep();
            }
        }
    }//GEN-LAST:event_txtStockMinimoKeyTyped

    private void txtStockMaximoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockMaximoKeyTyped
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();
        String codigo = txtStockMinimo.getText();
        int punto = codigo.indexOf(".")+1;
        
        if(punto == 0){
            if(!Character.isDigit(tecla) && tecla != java.awt.event.KeyEvent.VK_BACK_SPACE && tecla != KeyEvent.VK_PERIOD){
                evt.consume();
                getToolkit().beep();
            }
        }else{
            if(!Character.isDigit(tecla) && tecla != java.awt.event.KeyEvent.VK_BACK_SPACE){
                evt.consume();
                getToolkit().beep();
            }
        }
    }//GEN-LAST:event_txtStockMaximoKeyTyped

    private void txtStockActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockActualKeyTyped
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();
        String codigo = txtStockMinimo.getText();
        int punto = codigo.indexOf(".")+1;
        
        if(punto == 0){
            if(!Character.isDigit(tecla) && tecla != java.awt.event.KeyEvent.VK_BACK_SPACE && tecla != KeyEvent.VK_PERIOD){
                evt.consume();
                getToolkit().beep();
            }
        }else{
            if(!Character.isDigit(tecla) && tecla != java.awt.event.KeyEvent.VK_BACK_SPACE){
                evt.consume();
                getToolkit().beep();
            }
        }
    }//GEN-LAST:event_txtStockActualKeyTyped

    private void txtPrecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCompraKeyTyped
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();
        String codigo = txtStockMinimo.getText();
        int punto = codigo.indexOf(".")+1;
        
        if(punto == 0){
            if(!Character.isDigit(tecla) && tecla != java.awt.event.KeyEvent.VK_BACK_SPACE && tecla != KeyEvent.VK_PERIOD){
                evt.consume();
                getToolkit().beep();
            }
        }else{
            if(!Character.isDigit(tecla) && tecla != java.awt.event.KeyEvent.VK_BACK_SPACE){
                evt.consume();
                getToolkit().beep();
            }
        }
    }//GEN-LAST:event_txtPrecioCompraKeyTyped

    private void txtUtilidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUtilidadKeyTyped
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();
        String codigo = txtStockMinimo.getText();
        int punto = codigo.indexOf(".")+1;
        
        if(punto == 0){
            if(!Character.isDigit(tecla) && tecla != java.awt.event.KeyEvent.VK_BACK_SPACE && tecla != KeyEvent.VK_PERIOD){
                evt.consume();
                getToolkit().beep();
            }
        }else{
            if(!Character.isDigit(tecla) && tecla != java.awt.event.KeyEvent.VK_BACK_SPACE){
                evt.consume();
                getToolkit().beep();
            }
        }
    }//GEN-LAST:event_txtUtilidadKeyTyped

    private void txtPrecioVtaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVtaKeyTyped
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();
        String codigo = txtStockMinimo.getText();
        int punto = codigo.indexOf(".")+1;
        
        if(punto == 0){
            if(!Character.isDigit(tecla) && tecla != java.awt.event.KeyEvent.VK_BACK_SPACE && tecla != KeyEvent.VK_PERIOD){
                evt.consume();
                getToolkit().beep();
            }
        }else{
            if(!Character.isDigit(tecla) && tecla != java.awt.event.KeyEvent.VK_BACK_SPACE){
                evt.consume();
                getToolkit().beep();
            }
        }
    }//GEN-LAST:event_txtPrecioVtaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxLaboratorio;
    private javax.swing.JComboBox<String> cbxMarca;
    private javax.swing.JComboBox<String> cbxUndMedida;
    private com.toedter.calendar.JDateChooser dtpFechaVto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtPrecioVta;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtStockActual;
    private javax.swing.JTextField txtStockMaximo;
    private javax.swing.JTextField txtStockMinimo;
    private javax.swing.JTextField txtUtilidad;
    // End of variables declaration//GEN-END:variables
}
